// Variables var let const //
// var //
// var a = 5;
// var a = 6;
// console.log(a,a)
// {
//     var a = 20;
//     console.log(a)
// }


// let //
// let a = 4;
// let b = 5;
// {
//     let c = 20;
//     console.log(c)
// }
// console.log(a,b)


// const //
// const error //
// const name1 = "ram"
// console.log(name1)
// let name1 = "ram"
// console.log(name1)
// const run //
// const n2 = "rahul1"
// console.log(n2)
// const n3 = "rahul1"
// console.log(n3)


// Data Types in Js //
// let a = null;
// let b = 5;
// let c = "hi";
// let d = true;
// let e = Symbol("This is datatypes");
// let f = BigInt("9") + BigInt("1");
// let g = undefined;
// console.log(a, b, c, d, e, f, g)


// Objects in Js//
// const itemlist = {
//     "pen": 10,
//     "book": 11,
//     "bag": 12,
//     "shoes": 14,
// }
// console.log(itemlist["pen"])
// console.log(itemlist["book"])
// console.log(itemlist["bag"])
// console.log(itemlist["shoes"])


// Operators in Js //
// Arithmetic Operators //
// let a = 3;
// let b = 4;
// console.log("Sum of a and b is = ", (a + b))
// console.log("Sum of a and b is = ", (a - b))
// console.log("Sum of a and b is = ", (a * b))
// console.log("Sum of a and b is = ", (a ** b))
// console.log("Sum of a and b is = ", (a / b))
// console.log("Sum of a and b is = ", (a % b))
// console.log("Sum of a and b is = ", (a++))
// console.log("Sum of a and b is = ", (a--))


// Assignment Operators //
// let c = 10;
// let d = 11;
// console.log("Sum of c and d is = ", (c += d))
// console.log("Sum of c and d is = ", (c -= d))
// console.log("Sum of c and d is = ", (c *= d))
// console.log("Sum of c and d is = ", (c **= d))
// console.log("Sum of c and d is = ", (c /= d))
// console.log("Sum of c and d is = ", (c %= d))


// Comparison Operators //
// let x = 23;
// let y = 34;
// console.log("Sum of x and y is = ", (x == y))
// console.log("Sum of x and y is = ", (x != y))
// console.log("Sum of x and y is = ", (x === y))
// console.log("Sum of x and y is = ", (x !== y))
// console.log("Sum of x and y is = ", (x > y))
// console.log("Sum of x and y is = ", (x < y))
// console.log("Sum of x and y is = ", (x >= y))
// console.log("Sum of x and y is = ", (x <= y))


// Logical Operators //
// let q = 5;
// let r = 6;
// console.log(q>r && q==6)
// console.log(q<r || r==6)
// console.log(!true)
// console.log(!false)


// Conditional Statements in Js //
// let n = prompt("Hey whats your age?");
// n = Number.parseInt(n)
// if else statements //
// if(n>0) {
//     alert("This is a Valid age?");
// }
// else{
//     alert("This is an Invalid age?");
// }
// console.log(n)


// if, else if, else statements //
// if (n<0) {
//     alert("This is Invalid age?");
// }
// else if (n<10) {
//     alert("you are a kid?");
// }
// else if (n<20 && n>=15) {
//     alert("You can Drive after 20?");
// }
// else{
//     alert("You can Drive?")
// }
// console.log(n)
// console.log("done")


// ternary Operator //
// console.log("you can", n < 20 ? "not drive" : "drive")


// Loops in Js //
// For loop //
// print nums //
// for (let i = 0; i<50; i++) {
//     console.log(i);
// }


// For in loop //
// print in Object value a and obj[a] //
// let obj = {
//     "book": 1,
//     "pen": 2,
//     "shoes": 3,
// }
// for (let a in obj) {
//     console.log("This is my " + a + obj[a])
// }


// For of loop //
// obj is not itrabile //
// for (let a of obj) {
//     console.log("This is my " + a + obj[a])
// }


// While & do While loop //
// let n = prompt("Enter the value of n?");
// n = Number.parseInt(n)
// while loop //
// let i = 0;
// while(i<n) {
//     console.log(i)
//     i++;
// }


// do while loop //
// let i = 5;
// do{
//     console.log(i)
//     i++;
// }while (i<n)


// Function in Js // 
// basic function //
// function myFunction() {
//     console.log("Welcome in JS 1");
//     console.log("Welcome in JS 2");
//     console.log("Welcome in JS 3");
//     console.log("Welcome in JS 4");
//     console.log("Welcome in JS 5");
// }
// myFunction();
// Function run //
// function OneNumPrt(x, y) {
//     console.log("Done");
//     return 1 + (x + y) / 2
// }
// let a = 4;
// let b = 5;
// let c = 6;

// console.log("One Number Print b and c is ", OneNumPrt(b, c));
// console.log("One Number Print a and b is ", OneNumPrt(a, b));
// console.log("One Number Print a and c is ", OneNumPrt(a, c));
// Arrow function //
// const hello = () => {
//     console.log("Hey you")
//     return "hi"
// }
// function OneNumPrt(x, y) {
//     console.log("Done");
//     return 1 + (x + y) / 2
// }

// const sum = (p, q) => {
//     return p + q
// }
// let a = 4;
// let b = 5;
// let c = 6;

// console.log("One Number Print b and c is ", OneNumPrt(b, c));
// console.log("One Number Print a and b is ", OneNumPrt(a, b));
// console.log("One Number Print a and c is ", OneNumPrt(a, c));
// console.log(sum(10,5));
// hello();
// let d = hello();
// console.log(d);


// Strings in Js //





